name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - run: npm install && npm run build
    
      # 部署到 GitHub Pages
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
          token: ${{ secrets.MY_TOKEN }}
          repository-name: David-XIa001/JSON-internationalization
          BRANCH: main
          FOLDER: dist
          CLEAN: true
          commit-message: "Deploy by source"
